#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import{fileURLToPath}from'node:url';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),write=process.argv.includes('--write');
const V={
'4FiwPN8M1rM':{f:'A nearly five-minute painting-process clip whose transcript contains only repeated thanks; the route documents Choe working visually, but tools, sequence and result require the video.',p:['David Choe'],w:[],t:['painting process','visual record','transcript limitation'],b:[[10,'Painting footage with repeated thanks'],[274,'Closing thanks']]},
'5s_cO2JCL5Q':{f:'A brief Choe Show excerpt has Choe describe writing his own eulogy to remain present, wanting a complete life without regret and embracing death as he embraces life.',p:['David Choe'],w:['The Choe Show'],t:['death awareness','presence','eulogy','life without regret'],a:['death and mortality'],b:[[8,'Writing an imagined eulogy'],[21,'A complete life without regret']]},
'7NSYJIczwUY':{f:'Mangchi’s Reverse Birthday Song turns aging into a rough celebratory performance; the available lyric transcript is damaged, so only the birthday/aging refrain and live-song structure are dependable.',p:['David Choe','Steve Lee'],w:['Mangchi','Reverse Birthday Song'],t:['live music','aging','birthday','damaged lyrics'],a:['explicit language','unreliable automatic lyrics'],b:[[3,'Birthday and getting older'],[90,'Damaged middle verse'],[143,'Birthday close']]},
'8WqN0WcYtgQ':{f:'A seventeen-second behind-the-scenes Mangchi video-shoot clip has only decoder loops (“ping/panning”); it is retained as visual production evidence without invented action or dialogue.',p:['David Choe'],w:['Mangchi'],t:['behind the scenes','video shoot','decoder failure'],b:[[2,'Video-shoot footage'],[17,'Decoder loop at close']]},
'B4UD01U7pTw':{f:'A thirty-five-second mixed-media clip visually shows Choe creating; the transcript is punctuation and thanks, so medium changes and technique remain source-video facts rather than textual claims.',p:['David Choe'],w:[],t:['mixed media','visual record','transcript limitation'],b:[[0,'Mixed-media process'],[35,'Closing thanks']]},
'CnFR15MWKXE':{f:'A transcript-sparse Thumbs Up Season 4 trailer preserves the call to “hit the road” and the Thumbs Up America identity; itinerary and scenes must be read from the trailer images.',p:['David Choe'],w:['Thumbs Up Season 4','Thumbs Up America'],t:['travel trailer','road documentary','visual record'],a:['explicit language'],b:[[0,'Hit the road: Thumbs Up America']]},
'DInFITDqmkA':{f:'A short upload titled Mangchi contains conversation about favorite songs and video-game weapons rather than a clearly recoverable performance; the mismatch is retained instead of forcing it into band history.',p:['David Choe'],w:['Mangchi','Destiny'],t:['source mismatch','video games','transcript uncertainty'],b:[[0,'Favorite song and game loadout'],[127,'Scout rifle and Häkke weapon talk'],[143,'Brief close']]},
'FbJRcXuqpqs':{f:'A six-second Dirty Hands in San Francisco fragment contains only “The End”; it functions as a documentary end card, not a substantive alternate cut.',p:['David Choe','Harry Kim'],w:['Dirty Hands'],t:['documentary end card','San Francisco','transcript limitation'],b:[[6,'The End']]},
'FwXQfRF9h6w':{f:'An Igloo Hong mural clip in Rio preserves one line about a community playing field; the title identifies Herbert Baglione and Choe, while mural stages and local participants remain visual.',p:['David Choe','Herbert Baglione'],l:['Rio de Janeiro','Brazil'],w:['Igloo Hong'],t:['community mural','playing field','visual record'],b:[[0,'Community field and Rio mural context']]},
'G9CTAhKRCTo':{f:'A warm-up clip names Choe, El Mac and the Igloo Hong Super Crew before painting, but the decoder yields thanks and repetition; it is cataloged as pre-painting visual context.',p:['David Choe','El Mac'],w:['Igloo Hong'],t:['mural warm-up','artist crew','decoder failure'],b:[[0,'Crew warming up before painting']]},
'Ga9f_4K-j8c':{f:'A transcript-sparse clip identifies Choe painting at David Chang’s Momofuku Ko; the sole phrase “Action for God” does not support a fuller spoken summary.',p:['David Choe','David Chang'],l:['New York City'],w:['Momofuku Ko'],t:['restaurant painting','visual record','transcript limitation'],b:[[0,'Painting at Momofuku Ko']]},
'IM8oNL2-xIs':{f:'A live encore captures Die Antwoord’s Ninja joining Mangchi for an “I Love It” refrain, followed by thanks to Ninja and San Francisco’s Elbo Room; rough lyrics and a racial slur remain warned.',p:['David Choe','Steve Lee','Ninja'],l:['San Francisco'],w:['Mangchi','I Love It'],t:['live encore','guest performance','Elbo Room'],a:['racial slur','explicit language','rough lyrics'],b:[[0,'I Love It encore'],[22,'Repeated refrain'],[89,'Thanks to Ninja and Elbo Room']]},
'LcnoUWEscUY':{f:'A ten-second visual clip shows Ninja crowd-surfing during a Mangchi show at San Francisco’s Elbo Room; the transcript contains one shouted fragment and cannot describe the movement.',p:['Ninja','David Choe','Steve Lee'],l:['Elbo Room','San Francisco'],w:['Mangchi'],t:['crowd surfing','live music','visual record'],a:['explicit language'],b:[[10,'Ninja crowd-surfs during the live show']]},
'MP7SF5dVp70':{f:'Mangchi’s Gunk Boi opens with a school-shooting narrative and moves into repeated “get up” chants; the automatic lyrics are incomplete and are not silently repaired.',p:['David Choe','Steve Lee'],w:['Mangchi','Gunk Boi'],t:['song','school shooting','live chant','damaged lyrics'],a:['school shooting and gun violence','explicit language'],b:[[0,'Gunman narrative'],[61,'Repeated get-up chant'],[115,'Song close']]},
'TzEI4nsKhx4':{f:'A Facebook-office Super 8 painting clip is visually meaningful but textually unusable: the sole segment is a decoder repetition. It is linked to Choe’s Facebook mural work without narrating unseen details.',p:['David Choe'],l:['Facebook offices'],w:['Facebook office murals'],t:['Super 8','mural painting','decoder failure'],b:[[0,'Super 8 mural footage']]},
'VucJLf8Jbn0':{f:'A painting-at-Facebook clip contains only “Thank you” in the transcript; it is a visual record of Choe’s office work, not a separate narrated account.',p:['David Choe'],l:['Facebook offices'],w:['Facebook office murals'],t:['mural painting','visual record','transcript limitation'],b:[[0,'Painting in the Facebook offices']]},
'ZcaWMy_b9Ns':{f:'A Good Smile Factory painting clip identifies Choe and the Japan location through source metadata, while the transcript contains only thanks; the mural process remains visual.',p:['David Choe'],l:['Japan'],w:['Good Smile Factory mural'],t:['factory mural','Japan','visual record'],b:[[0,'Painting at Good Smile Factory']]},
'_Azb3sploI0':{f:'Mangchi’s I Love You compresses longing, hurt, hatred and forgiveness into a thirty-second song fragment that ends with enduring love and thanks.',p:['David Choe','Steve Lee'],w:['Mangchi','I Love You'],t:['love song','hurt','forgiveness'],a:['death wish in lyrics'],b:[[13,'Longing and hurt'],[29,'Hatred turns toward forgiveness']]},
'aPzKoSLopmc':{f:'A route labeled “David Choe ASMR live” contains only thanks and vocal filler; ASMR performance detail, setting and other participants cannot be recovered from its transcript.',p:['David Choe'],w:[],t:['ASMR','live clip','transcript limitation'],b:[[0,'Transcript-sparse ASMR clip']]},
'aXa4t8UGTOc':{f:'Mangchi’s The Best is a short, profane affirmation built around the repeated claim that the listener is the best; the middle automatic lyrics are damaged.',p:['David Choe','Steve Lee'],w:['Mangchi','The Best'],t:['affirmation song','live music','damaged lyrics'],a:['explicit language'],b:[[1,'You are the best refrain'],[71,'Damaged middle verse'],[108,'Who is the best?']]},
'eOtkM7egpnM':{f:'A second Good Smile Factory mural route is a short visual upload with only thanks transcribed; it remains a separate source URL while linking to the same Japan painting context.',p:['David Choe'],l:['Japan'],w:['Good Smile Factory mural'],t:['mural painting','duplicate visual context','transcript limitation'],b:[[0,'Good Smile Factory mural footage']]},
'g0SDGfXVzpc':{f:'A TigerBelly clip follows George Kimmel’s complaint that Khalyla attended The Choe Show while he was not invited, questions whether he applied seriously and ends with an attempt to arrange a remaining-week visit.',p:['George Kimmel','Khalyla','David Choe','Rainn Wilson'],w:['TigerBelly','The Choe Show','The Office','Creed'],t:['invitation','application','podcast banter'],a:['explicit language'],b:[[0,'Khalyla went; George was not invited'],[77,'Who would watch the show?'],[140,'Trying to set up a visit']]},
'kHJHdCnGnvA':{f:'A transcript-sparse Norway clip names Martin and ends twice; the title supplies Choe and Norway, but the recorded action cannot be responsibly reconstructed from one damaged line.',p:['David Choe'],l:['Norway'],w:[],t:['travel clip','visual record','transcript limitation'],b:[[0,'Norway footage and damaged closing line']]},
'mUsyh416654':{f:'A Mangchi video featuring Steve Lee has only a repeated decoder fragment; it is retained as band-video evidence with no invented lyrics or action.',p:['Steve Lee','David Choe'],w:['Mangchi'],t:['music video','Steve Lee','decoder failure'],b:[[27,'Mangchi video footage']]},
'mw6E0N8PZEM':{f:'A transcript-sparse Happy vs. Sad Choe Show clip contains only a reaction and thanks; its emotional contrast is source-title context, not recoverable dialogue.',p:['David Choe'],w:['The Choe Show'],t:['happy and sad','visual excerpt','transcript limitation'],b:[[0,'Happy-versus-sad visual excerpt']]},
'p2E_8DhelKQ':{f:'A Thumbs Up Season 4 connection clip has an entirely corrupted decoder segment; the title identifies an unexpected connection, but who connected and how require the source video.',p:['David Choe'],w:['Thumbs Up Season 4'],t:['unexpected connection','travel clip','decoder failure'],b:[[20,'Unexpected-connection visual clip']]},
'pknJx79BV7o':{f:'A Hulu trailer for The Choe Show has a repeated one-word decoder failure; it is cataloged as platform trailer evidence without manufacturing scenes or dialogue.',p:['David Choe'],w:['The Choe Show','Hulu'],t:['television trailer','platform promotion','decoder failure'],b:[[2,'Hulu trailer montage']]},
'pw_HXGxrJ9s':{f:'A twenty-six-second Choe/Joaquin Phoenix edit titled You Were Really Never Here has only “The” transcribed; the relationship to the film title is metadata, and montage meaning remains visual.',p:['David Choe','Joaquin Phoenix'],w:['You Were Never Really Here'],t:['fan edit','film montage','transcript limitation'],b:[[26,'Joaquin Phoenix and Choe montage']]},
'qs1yRqLkRm4':{f:'Mangchi’s These Are My People moves from lower-astral-plane and reptilian imagery through explicit surreal birth lyrics into the repeated chosen-community refrain.',p:['David Choe','Steve Lee'],w:['Mangchi','These Are My People'],t:['chosen community','occult imagery','surreal lyrics'],a:['explicit sexual and birth imagery','conspiracy and reptilian language'],b:[[0,'Lower astral plane'],[83,'Surreal fluorescent birth verse'],[181,'These are the people refrain']]},
'u2V3qYnhf3U':{f:'A five-second Choe Show trailer has an unusable non-English decoder loop; it is preserved as visual promotional evidence only.',p:['David Choe'],w:['The Choe Show'],t:['television trailer','decoder failure'],b:[[5,'The Choe Show trailer montage']]},
'zSuvEkr6TY0':{f:'A short art lesson shows Choe using an architecture presentation board for an underpainting, accepting bleeding material, misting color across it and ending by pointing to the best result.',p:['David Choe'],w:[],t:['underpainting','architecture board','spray mist','material experimentation'],b:[[8,'Painting on an architecture board'],[91,'Misting color over the surface'],[162,'The best thing he made']]}
};
const data=id=>JSON.parse(fs.readFileSync(path.join(ROOT,'data',`${id}.json`),'utf8'));
function rec(id,s){const d=data(id),dur=Number(d.segments?.at(-1)?.t||0),sparse=(d.segments?.length||0)<=2;return{episode_id:id,title:d.title,reviewed_on:'2026-08-13',description:s.f,summary:`${s.f} ${sparse?'Because the available transcript is sparse or corrupted, the archive deliberately limits the claim to title/provenance and recoverable words rather than inventing visual detail.':'The chapter map follows the recoverable route timeline; lyrics and visually dependent action remain limited where the automatic transcript is damaged.'}`,chapters:s.b.map(([t,title])=>({t,title})),people:s.p,places:s.l||[],works:s.w,themes:s.t,connections:[{to:'David Choe visual and performance archive',note:'This route remains independently addressable even when speech is sparse; its limitation is part of the editorial record.'}],content_warnings:s.a||[],publication_restrictions:[{t:0,rule:'Do not infer untranscribed actions, identities or lyrics from title metadata alone; consult the source video.'}],quality:{aggregate_segments:d.segments?.length||0,duration_seconds:dur,chapters:s.b.length,named_turns:0,transcript_limited:sparse||s.t.includes('decoder failure')||s.t.includes('transcript limitation')},source_notes:['Focus and chapter labels use only route title/provenance and recoverable transcript evidence.','Sparse or looped decoder output is recorded as a limitation, not repaired by guessing.'],speaker_policy:'Public route-level people may be listed from stable source metadata. No line-level speaker labels are assigned.'};}
let changed=0;for(const[id,s]of Object.entries(V)){const p=path.join(ROOT,'editorial',`${id}.json`),z=`${JSON.stringify(rec(id,s),null,2)}\n`;if(fs.existsSync(p)&&fs.readFileSync(p,'utf8')===z)continue;changed++;if(write)fs.writeFileSync(p,z);}if(!write&&changed){console.error(`${changed} visual editorial records are out of sync; run node scripts/build_visual_editorial.mjs --write`);process.exit(1);}console.log(`${Object.keys(V).length} visual/performance records validated; ${write?changed:0} editorial files written.`);
